// Builds everything the Worker serves as a static asset: the stylesheet, the
// three client bundles, and the vendored pdf.js. Deliberately a plain script —
// there is no bundler config to learn before you can change something.
import { execFileSync } from "node:child_process";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "public");

await rm(resolve(out, "assets"), { recursive: true, force: true });
await mkdir(resolve(out, "assets"), { recursive: true });
await mkdir(resolve(out, "assets/fonts"), { recursive: true });
await mkdir(resolve(out, "vendor/pdfjs"), { recursive: true });

// 0. Self-hosted IBM Plex Sans Arabic.
//
// Copied out of the npm package and served from our own origin, so an Arabic
// page makes no request to Google at all. That matters here beyond taste: the
// privacy policy on this site promises there are no third parties besides
// Cloudflare, Stripe and Resend, and a webfont request carries an IP address.
//
// The @font-face rules are generated rather than hand-written because of
// `unicode-range`. Those ranges are what stop an English page ever downloading
// 42 KB of Arabic glyphs, and they belong to the font rather than to us —
// reading them out of the package means a font upgrade cannot leave them stale.
//
// Weight 500 is included even though the original Google Fonts request did not
// ask for it: the site leans on `font-medium` throughout, and with only
// 400/600/700 present the CSS font-matching rules resolve 500 *down* to 400,
// quietly flattening every medium heading on the Arabic side.
const FONT_WEIGHTS = [400, 500, 600, 700];
const FONT_SUBSETS = ["arabic", "latin"];
const fontPackage = resolve(root, "node_modules/@fontsource/ibm-plex-sans-arabic");
const ranges = JSON.parse(await readFile(resolve(fontPackage, "unicode.json"), "utf8"));

const faces = [];
for (const subset of FONT_SUBSETS) {
  for (const weight of FONT_WEIGHTS) {
    const from = `ibm-plex-sans-arabic-${subset}-${weight}-normal.woff2`;
    const to = `plex-${subset}-${weight}.woff2`;
    await cp(resolve(fontPackage, "files", from), resolve(out, "assets/fonts", to));

    faces.push(
      [
        `@font-face {`,
        `  font-family: "IBM Plex Sans Arabic";`,
        `  font-style: normal;`,
        `  font-weight: ${weight};`,
        // `swap` over `block`: text in a fallback face for a moment beats a
        // heading that is not there at all on a slow connection.
        `  font-display: swap;`,
        `  src: url("/assets/fonts/${to}") format("woff2");`,
        `  unicode-range: ${ranges[subset]};`,
        `}`,
      ].join("\n"),
    );
  }
}

await writeFile(
  resolve(root, "src/styles/fonts.generated.css"),
  [
    "/* Generated by scripts/build.mjs — do not edit, it is overwritten on every",
    "   build. To change which weights exist, edit FONT_WEIGHTS in that file. */",
    "",
    faces.join("\n\n"),
    "",
  ].join("\n"),
);

// 1. Tailwind + Basecoat + our theme variables.
execFileSync(
  "npx",
  ["@tailwindcss/cli", "-i", "src/styles/app.css", "-o", "public/assets/app.css", "--minify"],
  { cwd: root, stdio: "inherit" },
);

// 2. Client bundles. `/vendor/*` is left external so pdf.js stays whole and
//    keeps its own worker file.
await esbuild.build({
  entryPoints: {
    upload: "src/client/upload.ts",
    viewer: "src/client/viewer.ts",
    tools: "src/client/tools.ts",
    dashboard: "src/client/dashboard.ts",
    pricing: "src/client/pricing.ts",
  },
  outdir: "public/assets",
  bundle: true,
  format: "esm",
  target: "es2022",
  minify: true,
  sourcemap: true,
  external: ["/vendor/*"],
  absWorkingDir: root,
});

// 3. Vendored pdf.js. Copied rather than bundled so upgrades are a version bump.
const pdfjs = resolve(root, "node_modules/pdfjs-dist/build");
for (const file of ["pdf.min.mjs", "pdf.worker.min.mjs"]) {
  await cp(resolve(pdfjs, file), resolve(out, "vendor/pdfjs", file));
}

console.log("built: public/assets (css + fonts + client bundles) and vendor/pdfjs");
